/*
Deployment script for tempDBScript

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "tempDBScript"
:setvar DefaultFilePrefix "tempDBScript"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[Customers]...';


GO
CREATE TABLE [dbo].[Customers] (
    [CustomerId] INT           NOT NULL,
    [FullName]   VARCHAR (100) NOT NULL,
    [City]       VARCHAR (50)  NOT NULL,
    [Segment]    VARCHAR (20)  NOT NULL,
    [IsActive]   BIT           NOT NULL,
    [CreatedOn]  DATE          NOT NULL
);


GO
PRINT N'Creating Table [dbo].[DeliveredOrders]...';


GO
CREATE TABLE [dbo].[DeliveredOrders] (
    [OrderId]     INT             NOT NULL,
    [CustomerId]  INT             NOT NULL,
    [OrderDate]   DATE            NOT NULL,
    [Amount]      DECIMAL (10, 2) NOT NULL,
    [Status]      VARCHAR (20)    NOT NULL,
    [PaymentMode] VARCHAR (20)    NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Orders]...';


GO
CREATE TABLE [dbo].[Orders] (
    [OrderId]     INT             NOT NULL,
    [CustomerId]  INT             NOT NULL,
    [OrderDate]   DATE            NOT NULL,
    [Amount]      DECIMAL (10, 2) NOT NULL,
    [Status]      VARCHAR (20)    NOT NULL,
    [PaymentMode] VARCHAR (20)    NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Products]...';


GO
CREATE TABLE [dbo].[Products] (
    [ProductId] INT             NOT NULL,
    [ProdName]  VARCHAR (100)   NULL,
    [Price]     DECIMAL (10, 2) NULL,
    [CreatedAt] DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([ProductId] ASC)
);


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Products]...';


GO
ALTER TABLE [dbo].[Products]
    ADD DEFAULT (getdate()) FOR [CreatedAt];


GO
PRINT N'Creating Procedure [dbo].[InsertCustomer]...';


GO
CREATE PROCEDURE InsertCustomer
    @Segment NVARCHAR(20),
    @CustomerID INT,
    @Name VARCHAR(100),
    @City VARCHAR(50),
    @Status BIT,
    @created DATE
AS
BEGIN
    INSERT INTO Customers (Segment, CustomerID, FullName, City, IsActive, CreatedOn)
    VALUES (@Segment, @CustomerID, @Name, @City, @Status, @created)
END
GO
PRINT N'Creating Procedure [dbo].[pracitce_select]...';


GO

-- Altering the procedure(or adding some condition)
CREATE PROCEDURE pracitce_select
@Segment VARCHAR(20)
AS
BEGIN
SELECT * FROM Customers where Segment = @Segment
END
GO
PRINT N'Creating Procedure [dbo].[Product_CRUD]...';


GO
CREATE PROCEDURE dbo.Product_CRUD
    @Action VARCHAR(10),
    @ProductId INT,
    @Name VARCHAR(100),
    @Price DECIMAL(10,2)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        IF @Action = 'CREATE'
        BEGIN
            IF OBJECT_ID('dbo.Products', 'U') IS NULL
            BEGIN
                CREATE TABLE dbo.Products
                (
                    ProductId INT PRIMARY KEY,
                    ProdName VARCHAR(100),
                    Price DECIMAL(10,2),
                    CreatedAt DATETIME DEFAULT GETDATE()
                );
            END
        END

        ELSE IF @Action = 'INSERT'
        BEGIN
            INSERT INTO dbo.Products (ProductId, ProdName, Price)
            VALUES (@ProductId, @Name, @Price);
        END

        ELSE IF @Action = 'SELECT'
        BEGIN
            SELECT *
            FROM dbo.Products
            WHERE ProductId = @ProductId;
        END

        ELSE IF @Action = 'UPDATE'
        BEGIN
            UPDATE dbo.Products
            SET ProdName = @Name,
                Price = @Price
            WHERE ProductId = @ProductId;
        END

        ELSE IF @Action = 'DELETE'
        BEGIN
            DELETE FROM dbo.Products
            WHERE ProductId = @ProductId;
        END
    END TRY
    BEGIN CATCH
        THROW;
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[StoredProcedureName]...';


GO
-- Create the stored procedure in the specified schema
CREATE PROCEDURE dbo.StoredProcedureName
    @param1 /*parameter name*/ int /*datatype_for_param1*/ = 0, /*default_value_for_param1*/
    @param2 /*parameter name*/ int /*datatype_for_param1*/ = 0 /*default_value_for_param2*/
-- add more stored procedure parameters here
AS
BEGIN
    -- body of the stored procedure
    SELECT @param1, @param2
END
GO
PRINT N'Update complete.';


GO
