/*
Deployment script for ScriptGenerateDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "ScriptGenerateDB"
:setvar DefaultFilePrefix "ScriptGenerateDB"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[PriceChangeLog]...';


GO
CREATE TABLE [dbo].[PriceChangeLog] (
    [LogId]     INT             IDENTITY (1, 1) NOT NULL,
    [ProductId] INT             NULL,
    [OldPrice]  DECIMAL (10, 2) NULL,
    [NewPrice]  DECIMAL (10, 2) NULL,
    [ChangedAt] DATETIME2 (7)   NULL,
    PRIMARY KEY CLUSTERED ([LogId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Products]...';


GO
CREATE TABLE [dbo].[Products] (
    [ProductId]   INT             IDENTITY (1, 1) NOT NULL,
    [ProductName] VARCHAR (100)   NOT NULL,
    [Category]    VARCHAR (50)    NOT NULL,
    [Price]       DECIMAL (10, 2) NULL,
    [StockQty]    INT             NULL,
    [IsActive]    BIT             NULL,
    [CreatedAt]   DATETIME2 (7)   NULL,
    PRIMARY KEY CLUSTERED ([ProductId] ASC)
);


GO
PRINT N'Creating Table [dbo].[ReorderLog]...';


GO
CREATE TABLE [dbo].[ReorderLog] (
    [LogId]     INT           IDENTITY (1, 1) NOT NULL,
    [ProductId] INT           NOT NULL,
    [Message]   VARCHAR (200) NOT NULL,
    [CreatedAt] DATETIME2 (7) NOT NULL,
    PRIMARY KEY CLUSTERED ([LogId] ASC)
);


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[PriceChangeLog]...';


GO
ALTER TABLE [dbo].[PriceChangeLog]
    ADD DEFAULT (sysdatetime()) FOR [ChangedAt];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Products]...';


GO
ALTER TABLE [dbo].[Products]
    ADD DEFAULT (sysdatetime()) FOR [CreatedAt];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Products]...';


GO
ALTER TABLE [dbo].[Products]
    ADD DEFAULT ((1)) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ReorderLog]...';


GO
ALTER TABLE [dbo].[ReorderLog]
    ADD DEFAULT (sysdatetime()) FOR [CreatedAt];


GO
PRINT N'Creating Check Constraint unnamed constraint on [dbo].[Products]...';


GO
ALTER TABLE [dbo].[Products] WITH NOCHECK
    ADD CHECK ([Price]>(0));


GO
PRINT N'Creating Check Constraint unnamed constraint on [dbo].[Products]...';


GO
ALTER TABLE [dbo].[Products] WITH NOCHECK
    ADD CHECK ([StockQty]>=(0));


GO
PRINT N'Creating View [dbo].[vw_ActiveProducts]...';


GO

CREATE   VIEW dbo.vw_ActiveProducts
AS
SELECT ProductName, Category, Price, StockQty
FROM dbo.Products
WHERE IsActive=1;
GO
PRINT N'Creating Trigger [dbo].[trg_vw_ActiveProducts_Insert]...';


GO

CREATE   TRIGGER dbo.trg_vw_ActiveProducts_Insert
ON dbo.vw_ActiveProducts
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO dbo.Products(ProductName, Category, Price, StockQty, IsActive)
    SELECT ProductName, Category, Price, StockQty, 1
    FROM inserted;
END;
GO
PRINT N'Creating Procedure [dbo].[usp_Cursor_FashionPriceIncrease]...';


GO

CREATE PROCEDURE dbo.usp_Cursor_FashionPriceIncrease
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Id INT, @Old DECIMAL(10,2), @New DECIMAL(10,2);

    DECLARE curFashion CURSOR FAST_FORWARD
    FOR SELECT ProductId, Price FROM dbo.Products WHERE Category='Fashion';

    BEGIN TRY
        BEGIN TRAN;

        OPEN curFashion;
        FETCH NEXT FROM curFashion INTO @Id, @Old;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            SET @New = ROUND(@Old * 1.05, 2);

            UPDATE dbo.Products SET Price=@New WHERE ProductId=@Id;

            INSERT INTO dbo.PriceChangeLog(ProductId, OldPrice, NewPrice)
            VALUES (@Id, @Old, @New);

            FETCH NEXT FROM curFashion INTO @Id, @Old;
        END;

        CLOSE curFashion;
        DEALLOCATE curFashion;
        COMMIT TRAN;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK;
        THROW;
    END CATCH;
END;
GO
PRINT N'Creating Procedure [dbo].[usp_Cursor_PrintProducts]...';


GO

CREATE PROCEDURE dbo.usp_Cursor_PrintProducts
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Id INT, @Name VARCHAR(100), @Price DECIMAL(10,2);

    DECLARE curProducts CURSOR FAST_FORWARD
    FOR SELECT ProductId, ProductName, Price FROM dbo.Products ORDER BY ProductId;

    OPEN curProducts;
    FETCH NEXT FROM curProducts INTO @Id, @Name, @Price;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        PRINT 'ID=' + CAST(@Id AS VARCHAR) + ' | ' + @Name + ' | ' + CAST(@Price AS VARCHAR);
        FETCH NEXT FROM curProducts INTO @Id, @Name, @Price;
    END;

    CLOSE curProducts;
    DEALLOCATE curProducts;
END;
GO
PRINT N'Creating Procedure [dbo].[usp_Cursor_ReorderLog]...';


GO

CREATE PROCEDURE dbo.usp_Cursor_ReorderLog
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE dbo.ReorderLog;

    DECLARE @Id INT, @Name VARCHAR(100), @Qty INT;

    DECLARE curLowStock CURSOR FAST_FORWARD
    FOR SELECT ProductId, ProductName, StockQty FROM dbo.Products WHERE StockQty < 30;

    OPEN curLowStock;
    FETCH NEXT FROM curLowStock INTO @Id, @Name, @Qty;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        INSERT INTO dbo.ReorderLog(ProductId, Message)
        VALUES (@Id, 'Reorder needed for ' + @Name + ' (Stock=' + CAST(@Qty AS VARCHAR) + ')');

        FETCH NEXT FROM curLowStock INTO @Id, @Name, @Qty;
    END;

    CLOSE curLowStock;
    DEALLOCATE curLowStock;
END;
GO
PRINT N'Creating Procedure [dbo].[usp_Setup_Tables]...';


GO

CREATE PROCEDURE dbo.usp_Setup_Tables
AS
BEGIN
    SET NOCOUNT ON;

    IF OBJECT_ID('dbo.Products','U') IS NOT NULL DROP TABLE dbo.Products;

    CREATE TABLE dbo.Products
    (
        ProductId INT IDENTITY PRIMARY KEY,
        ProductName VARCHAR(100) NOT NULL,
        Category VARCHAR(50) NOT NULL,
        Price DECIMAL(10,2) CHECK (Price > 0),
        StockQty INT CHECK (StockQty >= 0),
        IsActive BIT DEFAULT 1,
        CreatedAt DATETIME2 DEFAULT SYSDATETIME()
    );

    INSERT INTO dbo.Products(ProductName, Category, Price, StockQty)
    VALUES
    ('Wireless Mouse','Electronics',799,50),
    ('Mechanical Keyboard','Electronics',2499,25),
    ('Running Shoes','Fashion',1899,40),
    ('Water Bottle','Fitness',399,120),
    ('Laptop Backpack','Accessories',1499,35),
    ('USB-C Cable','Electronics',299,15),
    ('Gym Gloves','Fitness',499,28);
END;
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
CREATE TABLE [#__checkStatus] (
    id           INT            IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
    [Schema]     NVARCHAR (256),
    [Table]      NVARCHAR (256),
    [Constraint] NVARCHAR (256)
);

SET NOCOUNT ON;

DECLARE tableconstraintnames CURSOR LOCAL FORWARD_ONLY
    FOR SELECT SCHEMA_NAME([schema_id]),
               OBJECT_NAME([parent_object_id]),
               [name],
               0
        FROM   [sys].[objects]
        WHERE  [parent_object_id] IN (OBJECT_ID(N'dbo.Products'))
               AND [type] IN (N'F', N'C')
                   AND [object_id] IN (SELECT [object_id]
                                       FROM   [sys].[check_constraints]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0
                                       UNION
                                       SELECT [object_id]
                                       FROM   [sys].[foreign_keys]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0);

DECLARE @schemaname AS NVARCHAR (256);

DECLARE @tablename AS NVARCHAR (256);

DECLARE @checkname AS NVARCHAR (256);

DECLARE @is_not_trusted AS INT;

DECLARE @statement AS NVARCHAR (1024);

BEGIN TRY
    OPEN tableconstraintnames;
    FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
    WHILE @@fetch_status = 0
        BEGIN
            PRINT N'Checking constraint: ' + @checkname + N' [' + @schemaname + N'].[' + @tablename + N']';
            SET @statement = N'ALTER TABLE [' + @schemaname + N'].[' + @tablename + N'] WITH ' + CASE @is_not_trusted WHEN 0 THEN N'CHECK' ELSE N'NOCHECK' END + N' CHECK CONSTRAINT [' + @checkname + N']';
            BEGIN TRY
                EXECUTE [sp_executesql] @statement;
            END TRY
            BEGIN CATCH
                INSERT  [#__checkStatus] ([Schema], [Table], [Constraint])
                VALUES                  (@schemaname, @tablename, @checkname);
            END CATCH
            FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
        END
END TRY
BEGIN CATCH
    PRINT ERROR_MESSAGE();
END CATCH

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') >= 0
    CLOSE tableconstraintnames;

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') = -1
    DEALLOCATE tableconstraintnames;

SELECT N'Constraint verification failed:' + [Schema] + N'.' + [Table] + N',' + [Constraint]
FROM   [#__checkStatus];

IF @@ROWCOUNT > 0
    BEGIN
        DROP TABLE [#__checkStatus];
        RAISERROR (N'An error occurred while verifying constraints', 16, 127);
    END

SET NOCOUNT OFF;

DROP TABLE [#__checkStatus];


GO
PRINT N'Update complete.';


GO
